# remap prefix to C-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# set zsh as default shell
set -g default-command /bin/zsh

# index windows from 1
set -g base-index 1

# renumber windows when one is closed
set -g renumber-windows on

# use system clipboard
set -g set-clipboard on

# increase scrollback buffer
set -g history-limit 50000

# set copy mode to use vi motions
setw -g mode-keys vi

# increase left status length to show whole session name
set -g status-left-length 50

# remove vim mode switching delay
set -s escape-time 0

# set message display duration to 2 seconds
set -g display-time 2000

# enable mouse in tmux
set -g mouse on

# source .tmux.conf as suggested in 'man tmux'
bind R source ~/.config/tmux/tmux.conf \; display-message "config reloaded..."

# switch between last two windows
bind Space last-window

# open new window in current path
bind c new-window -c "#{pane_current_window}"

# split panes using \ and -
bind-key \\ split-window -h -c "#{pane_current_window}"
bind-key - split-window -v -c "#{pane_current_window}"

# put the status bar at the top of the terminal viewport
set -g status-position top

# justify status bar content to the right
set -g status-justify right

# make status bar black with with default font colour set to white
set -g status-style fg=white,bg=black

# clear default content from the left side of the status bar
set -g status-left ""

# make the session_name bold and blue
set -g status-right "#[bold,fg=blue] [#{session_name}] #[default]"

# format each window in the status bar as index:name
set -g window-status-format " #{window_index}:#{window_name} "

# make the current window in the status bar red
set -g window-status-current-format "#[bold,fg=red] #{window_index}:#{window_name} #[default]"
