#!/bin/bash

# Start hyprlock in the background
hyprlock &
HYPRLOCK_PID=$!

# Sleep for the timeout duration in the background
(
    sleep 300
    if ps -p $HYPRLOCK_PID > /dev/null; then
    	systemctl suspend
    fi
) &

# Wait for hyprlock to exit (when unlocked)
wait $HYPRLOCK_PID

# If hyprlock has exited, we can kill the sleep command
kill $!
